import type { ReviewDraft } from "@svl/domain";
export type ManagerJob = {
  id: string;
  label: string;
  customer: string | null;
  number: string | null;
  status: string | null;
  scheduledAt: string | null;
  technicians: string[];
  source: string | null;
  suggestionId?: string;
  active: boolean;
};
export type ReviewEvent = {
  id: string;
  action: string;
  actor: string;
  createdAt: string;
  version: number | null;
  reason: string | null;
  changes: Record<string, { before: unknown; after: unknown }>;
  externalId?: string | null;
};
export type ExportStep = {
  id: string;
  intentId: string;
  jobId: string;
  lineId: string | null;
  step: string;
  status: string;
  externalId: string | null;
  error: string | null;
  createdAt: string | null;
  retryQueued: boolean;
};
export type ReceiptDetail = {
  id: string;
  status: string;
  submittedAt: string;
  version: number;
  extractionId: string | null;
  draft: ReviewDraft;
  original: ReviewDraft;
  confidence: Record<string, number>;
  gps: { lat: number; lng: number } | null;
  pageCount: number;
  editable: boolean;
  steps: ExportStep[];
  events: ReviewEvent[];
  nextEventCursor: string | null;
  suggestions: ManagerJob[];
  correctionPending: boolean;
  clarification: string | null;
  canonicalReceiptId: string | null;
};
